### ISSUE TITLE
corsify creating unused readable stream

### ISSUE THREAD

**Issue by 0xCaliburSigma** [kwhitley/itty.dev#26]
Error:

A ReadableStream branch was created but never consumed. Such branches can be created, for instance, by calling the tee() method on a ReadableStream, or by calling the clone() method on a Request or Response object. If a branch is created but never consumed, it can force the runtime to buffer the entire body of the stream in memory, which may cause the Worker to exceed its memory limit and be terminated. To avoid this, ensure that all branches created are consumed.

 * Unused stream created:
    at corsify (index.js:62:113)
    at index.js:305:93

Code:
```
const { preflight, corsify } = cors({ origin: '*', allowMethods: ['GET'] });

const router = AutoRouter({
  base: '/',
  before: [preflight, customMiddleware],
  finally: [corsify]
});
```

**Comment by 0xCaliburSigma** [comment]
It isn't cause of my custom middleware either cause I removed it and the error persisted

**Comment by susickypavel** [comment]
Also facing the same issue If I use `waitUntil` in Cloudflare workers.

**Comment by rotemlevibigabid** [comment]
same here:

ReadableStream branches were created but never consumed. Such branches can be created, for instance, by calling the tee() method on a ReadableStream, or by calling the clone() method on a Request or Response object. If a branch is created but never consumed, it can force the runtime to buffer the entire body of the stream in memory, which may cause the Worker to exceed its memory limit and be terminated. To avoid this, ensure that all branches created are consumed.
